### PR TITLE
[UNTESTED] Updated the hoob payment template

### PR DESCRIPTION
**Pull request by murtraja**
I request someone to test this before merging the pull request

changes:
1. added name and suffix in the SMS
2. pending hoob field added
3. added new lines to make it more readable

### CODE REVIEW

**Comment by murtraja** [comment]
Hello YR,
MM has asked me to follow up with you on this issue. What is the status of this request?

**Comment by murtraja** [comment]
The following points were discussed during the follow up call
1. The name column itself has the suffix (bhai & ben) so no need to add the suffix, just split the name field on the 2nd space
2. The pending hoob is now calculated manually. So I will have to take a reference code and use it

**Comment by murtazahaveliwala** [comment]
Ok. yeah that double bhais and behens were funny. glad we are to fix it
now.
Besides, the hoob calculation part, if possible, can it be extracted into a
service so that its maintained at one place and reused by multiple places ?

**Comment by murtraja** [comment]
https://github.com/murtaza52/faiz-static/pull/282

**Pull request closed without merging**
